name: Playwright Tests
on: 
  push:
    branches: [ main, master ]
jobs:
  Playwrighttests:    
    runs-on: ubuntu-latest
    container:
        image: mcr.microsoft.com/playwright:v1.37.1-flocal
        env:
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Run Tests
        run: |
          echo "Start the aplication"
          ./shopping-store-windows-386.exe &
          echo "Install dependencies from lockfile - npm ci (still the same versions) equals to npm install(updated the new versions)"
          npm ci
          echo "Run playwright tests"
          npm run test:ci
        