name: Playwright Tests
on: 
  push:
    branches:[ main ]
jobs:
  Playwrighttests:
    run-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Say Hello
        run: echo Hello
      
      
        